version: '3.8'

services:
  app:
    build: .
    ports:
      - "9854:9854"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    expose:
      - 9854

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
