version: '3.8'

services:
  app:
    build: .
    networks:
      - internal
      - traefik-public
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wsserver.rule=Host(`your-domain.com`)"
      - "traefik.http.services.wsserver.loadbalancer.server.port=9854"
      - "traefik.docker.network=traefik-public"

  redis:
    image: redis:alpine
    networks:
      - internal
    volumes:
      - redis_data:/data
    # Remove exposed ports for security in production
    # ports:
    #   - "6379:6379"

networks:
  internal:
    driver: bridge
  traefik-public:
    external: true

volumes:
  redis_data:
